



# Powerlevel10k configuration for Zsh
# This file is automatically generated by p10k configure
# You can regenerate it by running `p10k configure`

# Enable Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit this file
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# Powerlevel10k configuration
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # Add your left prompt elements here
    # Common elements: context, dir, vcs, status, command_execution_time, etc.
    context
    dir
    vcs
    status
    command_execution_time
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # Add your right prompt elements here
    # Common elements: time, battery, load, etc.
    time
    battery
    load
    ram
    swap
)

# Basic configuration
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%(?:%F{green}➜%f :%F{red}➜%f )"

# Context configuration
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE="%n@%m"
typeset -g POWERLEVEL9K_CONTEXT_PREFIX=""
typeset -g POWERLEVEL9K_CONTEXT_SUFFIX=""

# Directory configuration
typeset -g POWERLEVEL9K_DIR_PATH_HIGHLIGHTING=true
typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR="  "
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

# VCS configuration
typeset -g POWERLEVEL9K_VCS_CHANGESET_HASH_LENGTH=6
typeset -g POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=true
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON=""
typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON=""
typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=""
typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=""

# Status configuration
typeset -g POWERLEVEL9K_STATUS_OK=true
typeset -g POWERLEVEL9K_STATUS_CROSS=true
typeset -g POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
typeset -g POWERLEVEL9K_STATUS_VERBOSE=false

# Time configuration
typeset -g POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
typeset -g POWERLEVEL9K_TIME_PREFIX=""
typeset -g POWERLEVEL9K_TIME_SUFFIX=""

# Battery configuration
typeset -g POWERLEVEL9K_BATTERY_CHARGING_ICON=""
typeset -g POWERLEVEL9K_BATTERY_CHARGED_ICON=""
typeset -g POWERLEVEL9K_BATTERY_DISCHARGING_ICON=""
typeset -g POWERLEVEL9K_BATTERY_LEVEL_CHANGED=true

# Load configuration
typeset -g POWERLEVEL9K_LOAD_ICON=""
typeset -g POWERLEVEL9K_LOAD_NORMAL_ICON=""
typeset -g POWERLEVEL9K_LOAD_WARNING_ICON=""
typeset -g POWERLEVEL9K_LOAD_CRITICAL_ICON=""

# RAM configuration
typeset -g POWERLEVEL9K_RAM_ICON=""
typeset -g POWERLEVEL9K_RAM_PREFIX=""
typeset -g POWERLEVEL9K_RAM_SUFFIX=""

# Swap configuration
typeset -g POWERLEVEL9K_SWAP_ICON=""
typeset -g POWERLEVEL9K_SWAP_PREFIX=""
typeset -g POWERLEVEL9K_SWAP_SUFFIX=""

# Command execution time configuration
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_ICON=""

# Icons
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=""

# Colors
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR_FOREGROUND=

# For a complete list of configuration options, run `p10k configure` or visit:
# https://github.com/romkatv/powerlevel10k#configuration



